
version: '3.8'
services:
  movies:
    image: raman84/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: raman84/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: raman84/paydth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: raman84/payrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
